### PR TITLE
Build with `transformers-0.6`/GHC 9.6

### PR DESCRIPTION
**Pull request by ocharles**
Confirmed to build with `allow-newer`.

### CODE REVIEW

**Comment by ocharles** [comment]
@jeffreyrosenbluth Ping. I'm happy to help maintain this library if you need any extra help!

**Comment by jeffreyrosenbluth** [comment]
Hi Ollie,
Sorry for the delayed response. I’m no longer very involved in the Haskell community, I jumped ship to Rust.
I’d be happy to add you as a maintainer, just let me know your Hackage ID.

Cheers

Jeff

**Comment by ocharles** [comment]
Hey, no problem! Yes, I'd be happy to help - can you add me as a collaborator to this repo (or transfer it to me, I don't mind which). My Hackage username is `OliverCharles`

**Comment by jeffreyrosenbluth** [comment]
I added you as a maintainer. Sorry this took so long.

Cheers

Jeff

**Comment by ocharles** [comment]
Fixed in https://hackage.haskell.org/package/lucid-svg-0.7.2.0 - thanks!

**Pull request closed without merging**
